## Sample .travis.yml file for use with metacran/r-builder
## See https://github.com/metacran/r-builder for details.
language: r 
r:
  - oldrel
  - release
  - devel
cache: packages

before_install:
  - cd ./glmmTMB

notifications:
  email:
    on_success: change
    on_failure: change

